name: Bygg og deploy master branch

on:
  push:
    branches:
      - 'master'

env:
  GITHUB_TOKEN: ${{ secrets.GITGUB_TOKEN }}
  APP_IMAGE: docker.pkg.github.com/${{ github.repository }}/arbeidsgiver-permittering
  IMAGE: docker.pkg.github.com/${{ github.repository }}/arbeidsgiver-permittering:${{ github.sha }}

  jobs:
    bygg:
      name: Bygg
      runs-on: ubuntu-latest
      steps:
      - name: Lukk deployment-issues
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['deploy']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Installer avhengigheter (npm ci)
        run: npm ci --no-optional

      - name: Bygg (npm run build)
        run: npm run build-prod

      - name: Bygg, tag og push docker image
        run: |
          docker build --tag $IMAGE --tag $APP_IMAGE:latest .
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_REPOSITORY --password-stdin
          docker push $APP_IMAGE

      - name: Generere nais variabler for prod
        run: |
          cat > nais/prod-values.yaml << EOF
          ingress:
            - https://arbeidsgiver.nav.no/arbeidsgiver-permittering
          EOF

      - name: Generere nais variabler for dev
        run: |
          cat > nais/dev-values.yaml << EOF
          ingress:
            - https://arbeidsgiver-q.nav.no/arbeidsgiver-permittering
          EOF

  deploy-dev-sbs:
    name: Deploy til dev-sbs
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Deploy til dev-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais/nais.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-values.yaml
          

  deploy-prod-sbs:
    name: Deploy til prod-sbs
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Deploy til prod-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/prod-values.yaml




